### ISSUE TITLE
Best practice question

### ISSUE THREAD

**Issue by MostHated** [aryehof/dart-eventsubscriber#1]
Hey there, 
   Thanks for making these packages (Event and EventSubscriber). I just started using them yesterday and mixing them with the "[get_it](https://pub.dev/packages/get_it)" service locator package has solved several issues I was having when trying to use only the Provider package.

I had a question though about a statement from the documentation. You mentioned, "best practice is that generally on notification one queries the domain model directly, rather than having arguments deliver data to a consumer of the domain model". You then say "The supply of data shown here is by way of example only." 

I am guessing that means the example is not actually the best way to go about using the package. Do you happen to have an example of what the actual best-practice way of using it might be compared to what was shown? I definitely would like to make sure I am learning and implementing things as properly as I can.

Thanks!
-MH

**Comment by aryehof** [comment]
Hi. It's more of a convention than a rule when dealing with a separate domain model. One can choose to pass information about the event with the event, but with complex systems over time, lots of events with information attached can be hard to manage. It will typically lead to decisions about the problem domain being placed in _one_ of the consumers of the model (like a UI), rather than all being in the problem domain model.

It's rare to actually have a separate object domain model these days, so my thought is not to worry too much and just pass data with the event, or instead just notify and then query the model... as you see fit.

Hopefully this helps a bit?
